[tool.poetry]
name = "coffee-shop"
version = "0.1.0"
description = ""
authors = ["Tatiana Carrascossa <tatiana.carrascossa@entelgy.com>"]

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
